In [3]:
import numpy as np

In [4]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

In [12]:
print("Matriks A :")
print(A)
print()
print("Matriks B :")
print(B)

Matriks A :
[[1 2]
 [7 8]]

Matriks B :
[[3 5]
 [1 6]]


### 1. 2*A

In [48]:
Perkalian = 2*A
print(Perkalian)

[[ 2  4]
 [14 16]]


### 2. 2+A

In [49]:
Penjumlahan = 2+A
print(Penjumlahan)

[[ 3  4]
 [ 9 10]]


### 3. A+B

In [50]:
Penjumlahan_Matriks = A+B
print(Penjumlahan_Matriks)

[[ 4  7]
 [ 8 14]]


### 4. A-B

In [51]:
Penjumlahan_Matriks = A-B
print(Penjumlahan_Matriks)

[[-2 -3]
 [ 6  2]]


### 5. determinan A

In [52]:
print('determinan matriks A = ', np.linalg.det(A))

determinan matriks A =  -6.0


### 6. invers dari B, simpan jadi matriks D

In [53]:
D = np.linalg.inv(B)
print(D)

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


### 7. transpose D

In [54]:
Trans_D = np.transpose(D)
print(Trans_D)

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


### 8. nilai eigen dan vektor eigen dari A dan B

In [55]:
print('Nilai Eigen Matriks A = ', np.linalg.eig(A)[0])
print('Nilai Eigen Matriks B = ', np.linalg.eig(B)[0])

Nilai Eigen Matriks A =  [-0.62347538  9.62347538]
Nilai Eigen Matriks B =  [1.8074176 7.1925824]


In [56]:
print('Vektor Eigen Matriks A = ', np.linalg.eig(A)[1])
print('Vektor Eigen Matriks A = ', np.linalg.eig(B)[1])

Vektor Eigen Matriks A =  [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]
Vektor Eigen Matriks A =  [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


### 9. Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [57]:
perkalian_entry = B*D
print("Perkalian Entry")
print(perkalian_entry)

Perkalian Entry
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [58]:
print('Perkalian Matriks')
perkalian_matriks = np.matmul(B,D)
print(perkalian_matriks)

Perkalian Matriks
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [59]:
print("Perkalian Entry\t:")
print(perkalian_entry)
print()
print('Perkalian Matriks :')
print(perkalian_matriks)

Perkalian Entry	:
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]

Perkalian Matriks :
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


#### Kesimpulan : Perbedaan pada perkalian entry dan perkalian matriks yaitu terletak pada hasilnya berbeda dan proses perhitungannyapun berbeda.